import asyncio
import json
import uuid
import shutil
from datetime import datetime
from pathlib import Path
from typing import Tuple
import logging

from backend.config import settings

logger = logging.getLogger(__name__)


async def generate_diy_report(
    project_description: str,
    experience_level: str
) -> Tuple[Path, str]:
    """
    Generates a DIY report by calling CrewAI and creating PDF.
    
    Args:
        project_description: Description of the DIY project
        experience_level: User's experience level (beginner/experienced/professional)
    
    Returns:
        Tuple of (pdf_path, file_id)
    
    Raises:
        Exception: If PDF generation fails
    """
    try:
        logger.info("Starting DIY report generation", extra={"excerpt": project_description[:80]})
        
        # Generate unique file ID
        file_id = uuid.uuid4().hex[:12]
        
        # Note: Experience level can be used to customize the report in future
        # For now, we use the project description as the topic
        
        # Call CrewAI via Python
        # We'll import and call the existing convert_report_to_pdf function
        # This runs the crew and generates the PDF
        
        # Change to CrewAI working directory
        crewai_dir = Path(settings.crewai_working_dir)
        outputs_dir = Path(settings.outputs_dir)
        downloads_dir = Path(settings.downloads_dir)

        if not crewai_dir.exists():
            raise FileNotFoundError(f"CrewAI working directory not found: {crewai_dir}")

        outputs_dir.mkdir(parents=True, exist_ok=True)
        downloads_dir.mkdir(parents=True, exist_ok=True)

        logger.debug(
            "CrewAI paths resolved",
            extra={
                "crewai_dir": str(crewai_dir),
                "outputs_dir": str(outputs_dir),
                "downloads_dir": str(downloads_dir),
            }
        )

        # Build payload for CrewAI
        payload = {
            "topic": project_description,
            "current_year": str(datetime.utcnow().year),
            "experience_level": experience_level,
        }

        python_code = f"""
import json
import sys
import pathlib

root = pathlib.Path(r"{crewai_dir}")
sys.path.insert(0, str(root / "src"))

from diy.main import run

inputs = json.loads(sys.argv[1])
run(inputs)
"""

        # Run CrewAI command with JSON payload
        process = await asyncio.create_subprocess_exec(
            "python", "-c",
            python_code,
            json.dumps(payload),
            cwd=str(crewai_dir),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE
        )
        
        stdout, stderr = await process.communicate()

        stdout_text = stdout.decode().strip()
        stderr_text = stderr.decode().strip()
        
        if process.returncode != 0:
            logger.error(
                "CrewAI execution failed",
                extra={
                    "returncode": process.returncode,
                    "stderr": stderr_text,
                    "stdout": stdout_text,
                }
            )
            raise Exception(f"Failed to generate report: {stderr_text or 'unknown error'}")
        
        logger.debug(
            "CrewAI execution completed",
            extra={
                "stdout": stdout_text,
                "stderr": stderr_text,
            }
        )
        
        # Find the generated PDF
        pdf_files = list(outputs_dir.glob("*.pdf"))
        
        if not pdf_files:
            existing_files = [p.name for p in outputs_dir.glob("*")]
            logger.error(
                "No PDF generated by CrewAI",
                extra={"outputs_dir": str(outputs_dir), "files_found": existing_files}
            )
            raise Exception("No PDF was generated")
        
        # Get the most recently created PDF
        latest_pdf = max(pdf_files, key=lambda p: p.stat().st_mtime)
        
        # Copy to downloads directory with unique ID
        dest_pdf = downloads_dir / f"{file_id}.pdf"
        shutil.copy2(latest_pdf, dest_pdf)
        
        logger.info(
            "PDF generated successfully",
            extra={
                "source_pdf": str(latest_pdf),
                "stored_pdf": str(dest_pdf),
                "file_id": file_id,
            }
        )
        
        return dest_pdf, file_id
        
    except Exception as e:
        logger.exception("Error generating DIY report")
        raise

